filter:
    excluded_paths: [tests/*]

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        return_doc_comments: true
        parameter_doc_comments: true
        optional_parameters_at_the_end: true
        more_specific_types_in_doc_comments: true
        encourage_single_quotes: true
        align_assignments: true

tools:
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['src']
  php_loc:
    enabled: true
    excluded_dirs: [vendor, spec, stubs]

coding_style:
    php:
        spaces:
            around_operators:
                negation: true
        braces:
            classes_functions:
                class: new-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: false
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower